version: '3.7'
services:
  backend:
    build: ./backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      TEST_DATABASE_URI: ${TEST_DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    container_name: frontend
    
  frontend:
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    container_name: frontend
  nginx:
    build: ./nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./cne-sfia2-brief/nginx/nginx.conf
      target: /etc/nginx/nginx.conf
